# Generated by Django 2.0.3 on 2018-04-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='code',
            field=models.CharField(default='x', max_length=5),
        ),
    ]
