# Generated by Django 2.0.2 on 2018-03-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180313_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='twilio_phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
